### ISSUE TITLE
[버그] 주소록에 이름이 저장되어 있는데 대화리스트에는 전화번호로만 내용이 보임

### ISSUE THREAD

**Issue by pig039** [kwzhang/tinytalk#44]
1. 주소록에 저장되어 있는 이름으로 Text Message를 보냄
2. 대화리스트에는 전화 번호로 보여짐

**Comment by kwzhang** [comment]
이름 지정 이전에 대화방을 생성하면 상대방 전화번호가 대화방 명이됩니다.
